# Generated by Django 5.0.7 on 2024-07-22 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0002_alter_category_options_article_articleview'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='is_sold',
        ),
        migrations.AddField(
            model_name='articleview',
            name='was_viewed',
            field=models.BooleanField(default=False),
        ),
    ]
