# Generated by Django 5.0.7 on 2024-07-31 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientspace', '0002_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='encrypted_passAT',
            field=models.BinaryField(blank=True, null=True),
        ),
    ]
